/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WhatIsAranciniRouteImport } from './routes/what-is-arancini'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SamarbeidRouteImport } from './routes/samarbeid'
import { Route as PilotRouteImport } from './routes/pilot'
import { Route as NextPopupRouteImport } from './routes/next-popup'
import { Route as ForBarerRouteImport } from './routes/for-barer'
import { Route as FinnOssRouteImport } from './routes/finn-oss'
import { Route as EnRouteImport } from './routes/en'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as A3f8c91e7b4d2f60goldofsicilyDottxtRouteImport } from './routes/a3f8c91e7b4d2f60goldofsicily[.]txt'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PilotIndexRouteImport } from './routes/pilot.index'
import { Route as EnIndexRouteImport } from './routes/en.index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as StederSlugRouteImport } from './routes/steder.$slug'
import { Route as PilotLeverandorRouteImport } from './routes/pilot.leverandor'
import { Route as EnWhatIsAranciniRouteImport } from './routes/en.what-is-arancini'
import { Route as EnNextPopupRouteImport } from './routes/en.next-popup'
import { Route as EnForBarsRouteImport } from './routes/en.for-bars'
import { Route as EnFindUsRouteImport } from './routes/en.find-us'
import { Route as EnCollaborateRouteImport } from './routes/en.collaborate'
import { Route as EnAboutRouteImport } from './routes/en.about'
import { Route as AdminPopupRouteImport } from './routes/admin/popup'
import { Route as AdminNewsletterRouteImport } from './routes/admin/newsletter'
import { Route as AdminInquiriesRouteImport } from './routes/admin/inquiries'
import { Route as AdminAccountingRouteImport } from './routes/admin/accounting'
import { Route as AdminSlugRouteImport } from './routes/admin/$slug'
import { Route as EnVenuesSlugRouteImport } from './routes/en.venues.$slug'
import { Route as ApiSeoNotifyRouteImport } from './routes/api/seo.notify'
import { Route as ApiPublicV1ModuleWidgetsRouteImport } from './routes/api/public/v1/module.widgets'
import { Route as ApiPublicV1ModuleOrganizationRouteImport } from './routes/api/public/v1/module.organization'
import { Route as ApiPublicV1ModuleInfoRouteImport } from './routes/api/public/v1/module.info'
import { Route as ApiPublicV1ModuleHealthRouteImport } from './routes/api/public/v1/module.health'
import { Route as ApiPublicV1ModuleOrganizationOrgIdRouteImport } from './routes/api/public/v1/module.organization.$orgId'

const WhatIsAranciniRoute = WhatIsAranciniRouteImport.update({
  id: '/what-is-arancini',
  path: '/what-is-arancini',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SamarbeidRoute = SamarbeidRouteImport.update({
  id: '/samarbeid',
  path: '/samarbeid',
  getParentRoute: () => rootRouteImport,
} as any)
const PilotRoute = PilotRouteImport.update({
  id: '/pilot',
  path: '/pilot',
  getParentRoute: () => rootRouteImport,
} as any)
const NextPopupRoute = NextPopupRouteImport.update({
  id: '/next-popup',
  path: '/next-popup',
  getParentRoute: () => rootRouteImport,
} as any)
const ForBarerRoute = ForBarerRouteImport.update({
  id: '/for-barer',
  path: '/for-barer',
  getParentRoute: () => rootRouteImport,
} as any)
const FinnOssRoute = FinnOssRouteImport.update({
  id: '/finn-oss',
  path: '/finn-oss',
  getParentRoute: () => rootRouteImport,
} as any)
const EnRoute = EnRouteImport.update({
  id: '/en',
  path: '/en',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const A3f8c91e7b4d2f60goldofsicilyDottxtRoute =
  A3f8c91e7b4d2f60goldofsicilyDottxtRouteImport.update({
    id: '/a3f8c91e7b4d2f60goldofsicily.txt',
    path: '/a3f8c91e7b4d2f60goldofsicily.txt',
    getParentRoute: () => rootRouteImport,
  } as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PilotIndexRoute = PilotIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PilotRoute,
} as any)
const EnIndexRoute = EnIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EnRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const StederSlugRoute = StederSlugRouteImport.update({
  id: '/steder/$slug',
  path: '/steder/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PilotLeverandorRoute = PilotLeverandorRouteImport.update({
  id: '/leverandor',
  path: '/leverandor',
  getParentRoute: () => PilotRoute,
} as any)
const EnWhatIsAranciniRoute = EnWhatIsAranciniRouteImport.update({
  id: '/what-is-arancini',
  path: '/what-is-arancini',
  getParentRoute: () => EnRoute,
} as any)
const EnNextPopupRoute = EnNextPopupRouteImport.update({
  id: '/next-popup',
  path: '/next-popup',
  getParentRoute: () => EnRoute,
} as any)
const EnForBarsRoute = EnForBarsRouteImport.update({
  id: '/for-bars',
  path: '/for-bars',
  getParentRoute: () => EnRoute,
} as any)
const EnFindUsRoute = EnFindUsRouteImport.update({
  id: '/find-us',
  path: '/find-us',
  getParentRoute: () => EnRoute,
} as any)
const EnCollaborateRoute = EnCollaborateRouteImport.update({
  id: '/collaborate',
  path: '/collaborate',
  getParentRoute: () => EnRoute,
} as any)
const EnAboutRoute = EnAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => EnRoute,
} as any)
const AdminPopupRoute = AdminPopupRouteImport.update({
  id: '/popup',
  path: '/popup',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNewsletterRoute = AdminNewsletterRouteImport.update({
  id: '/newsletter',
  path: '/newsletter',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInquiriesRoute = AdminInquiriesRouteImport.update({
  id: '/inquiries',
  path: '/inquiries',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAccountingRoute = AdminAccountingRouteImport.update({
  id: '/accounting',
  path: '/accounting',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSlugRoute = AdminSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => AdminRoute,
} as any)
const EnVenuesSlugRoute = EnVenuesSlugRouteImport.update({
  id: '/venues/$slug',
  path: '/venues/$slug',
  getParentRoute: () => EnRoute,
} as any)
const ApiSeoNotifyRoute = ApiSeoNotifyRouteImport.update({
  id: '/api/seo/notify',
  path: '/api/seo/notify',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1ModuleWidgetsRoute =
  ApiPublicV1ModuleWidgetsRouteImport.update({
    id: '/api/public/v1/module/widgets',
    path: '/api/public/v1/module/widgets',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicV1ModuleOrganizationRoute =
  ApiPublicV1ModuleOrganizationRouteImport.update({
    id: '/api/public/v1/module/organization',
    path: '/api/public/v1/module/organization',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicV1ModuleInfoRoute = ApiPublicV1ModuleInfoRouteImport.update({
  id: '/api/public/v1/module/info',
  path: '/api/public/v1/module/info',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1ModuleHealthRoute = ApiPublicV1ModuleHealthRouteImport.update({
  id: '/api/public/v1/module/health',
  path: '/api/public/v1/module/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1ModuleOrganizationOrgIdRoute =
  ApiPublicV1ModuleOrganizationOrgIdRouteImport.update({
    id: '/$orgId',
    path: '/$orgId',
    getParentRoute: () => ApiPublicV1ModuleOrganizationRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/a3f8c91e7b4d2f60goldofsicily.txt': typeof A3f8c91e7b4d2f60goldofsicilyDottxtRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/en': typeof EnRouteWithChildren
  '/finn-oss': typeof FinnOssRoute
  '/for-barer': typeof ForBarerRoute
  '/next-popup': typeof NextPopupRoute
  '/pilot': typeof PilotRouteWithChildren
  '/samarbeid': typeof SamarbeidRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/what-is-arancini': typeof WhatIsAranciniRoute
  '/admin/$slug': typeof AdminSlugRoute
  '/admin/accounting': typeof AdminAccountingRoute
  '/admin/inquiries': typeof AdminInquiriesRoute
  '/admin/newsletter': typeof AdminNewsletterRoute
  '/admin/popup': typeof AdminPopupRoute
  '/en/about': typeof EnAboutRoute
  '/en/collaborate': typeof EnCollaborateRoute
  '/en/find-us': typeof EnFindUsRoute
  '/en/for-bars': typeof EnForBarsRoute
  '/en/next-popup': typeof EnNextPopupRoute
  '/en/what-is-arancini': typeof EnWhatIsAranciniRoute
  '/pilot/leverandor': typeof PilotLeverandorRoute
  '/steder/$slug': typeof StederSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/en/': typeof EnIndexRoute
  '/pilot/': typeof PilotIndexRoute
  '/api/seo/notify': typeof ApiSeoNotifyRoute
  '/en/venues/$slug': typeof EnVenuesSlugRoute
  '/api/public/v1/module/health': typeof ApiPublicV1ModuleHealthRoute
  '/api/public/v1/module/info': typeof ApiPublicV1ModuleInfoRoute
  '/api/public/v1/module/organization': typeof ApiPublicV1ModuleOrganizationRouteWithChildren
  '/api/public/v1/module/widgets': typeof ApiPublicV1ModuleWidgetsRoute
  '/api/public/v1/module/organization/$orgId': typeof ApiPublicV1ModuleOrganizationOrgIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/a3f8c91e7b4d2f60goldofsicily.txt': typeof A3f8c91e7b4d2f60goldofsicilyDottxtRoute
  '/about': typeof AboutRoute
  '/finn-oss': typeof FinnOssRoute
  '/for-barer': typeof ForBarerRoute
  '/next-popup': typeof NextPopupRoute
  '/samarbeid': typeof SamarbeidRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/what-is-arancini': typeof WhatIsAranciniRoute
  '/admin/$slug': typeof AdminSlugRoute
  '/admin/accounting': typeof AdminAccountingRoute
  '/admin/inquiries': typeof AdminInquiriesRoute
  '/admin/newsletter': typeof AdminNewsletterRoute
  '/admin/popup': typeof AdminPopupRoute
  '/en/about': typeof EnAboutRoute
  '/en/collaborate': typeof EnCollaborateRoute
  '/en/find-us': typeof EnFindUsRoute
  '/en/for-bars': typeof EnForBarsRoute
  '/en/next-popup': typeof EnNextPopupRoute
  '/en/what-is-arancini': typeof EnWhatIsAranciniRoute
  '/pilot/leverandor': typeof PilotLeverandorRoute
  '/steder/$slug': typeof StederSlugRoute
  '/admin': typeof AdminIndexRoute
  '/en': typeof EnIndexRoute
  '/pilot': typeof PilotIndexRoute
  '/api/seo/notify': typeof ApiSeoNotifyRoute
  '/en/venues/$slug': typeof EnVenuesSlugRoute
  '/api/public/v1/module/health': typeof ApiPublicV1ModuleHealthRoute
  '/api/public/v1/module/info': typeof ApiPublicV1ModuleInfoRoute
  '/api/public/v1/module/organization': typeof ApiPublicV1ModuleOrganizationRouteWithChildren
  '/api/public/v1/module/widgets': typeof ApiPublicV1ModuleWidgetsRoute
  '/api/public/v1/module/organization/$orgId': typeof ApiPublicV1ModuleOrganizationOrgIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/a3f8c91e7b4d2f60goldofsicily.txt': typeof A3f8c91e7b4d2f60goldofsicilyDottxtRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/en': typeof EnRouteWithChildren
  '/finn-oss': typeof FinnOssRoute
  '/for-barer': typeof ForBarerRoute
  '/next-popup': typeof NextPopupRoute
  '/pilot': typeof PilotRouteWithChildren
  '/samarbeid': typeof SamarbeidRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/what-is-arancini': typeof WhatIsAranciniRoute
  '/admin/$slug': typeof AdminSlugRoute
  '/admin/accounting': typeof AdminAccountingRoute
  '/admin/inquiries': typeof AdminInquiriesRoute
  '/admin/newsletter': typeof AdminNewsletterRoute
  '/admin/popup': typeof AdminPopupRoute
  '/en/about': typeof EnAboutRoute
  '/en/collaborate': typeof EnCollaborateRoute
  '/en/find-us': typeof EnFindUsRoute
  '/en/for-bars': typeof EnForBarsRoute
  '/en/next-popup': typeof EnNextPopupRoute
  '/en/what-is-arancini': typeof EnWhatIsAranciniRoute
  '/pilot/leverandor': typeof PilotLeverandorRoute
  '/steder/$slug': typeof StederSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/en/': typeof EnIndexRoute
  '/pilot/': typeof PilotIndexRoute
  '/api/seo/notify': typeof ApiSeoNotifyRoute
  '/en/venues/$slug': typeof EnVenuesSlugRoute
  '/api/public/v1/module/health': typeof ApiPublicV1ModuleHealthRoute
  '/api/public/v1/module/info': typeof ApiPublicV1ModuleInfoRoute
  '/api/public/v1/module/organization': typeof ApiPublicV1ModuleOrganizationRouteWithChildren
  '/api/public/v1/module/widgets': typeof ApiPublicV1ModuleWidgetsRoute
  '/api/public/v1/module/organization/$orgId': typeof ApiPublicV1ModuleOrganizationOrgIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/a3f8c91e7b4d2f60goldofsicily.txt'
    | '/about'
    | '/admin'
    | '/en'
    | '/finn-oss'
    | '/for-barer'
    | '/next-popup'
    | '/pilot'
    | '/samarbeid'
    | '/sitemap.xml'
    | '/what-is-arancini'
    | '/admin/$slug'
    | '/admin/accounting'
    | '/admin/inquiries'
    | '/admin/newsletter'
    | '/admin/popup'
    | '/en/about'
    | '/en/collaborate'
    | '/en/find-us'
    | '/en/for-bars'
    | '/en/next-popup'
    | '/en/what-is-arancini'
    | '/pilot/leverandor'
    | '/steder/$slug'
    | '/admin/'
    | '/en/'
    | '/pilot/'
    | '/api/seo/notify'
    | '/en/venues/$slug'
    | '/api/public/v1/module/health'
    | '/api/public/v1/module/info'
    | '/api/public/v1/module/organization'
    | '/api/public/v1/module/widgets'
    | '/api/public/v1/module/organization/$orgId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/a3f8c91e7b4d2f60goldofsicily.txt'
    | '/about'
    | '/finn-oss'
    | '/for-barer'
    | '/next-popup'
    | '/samarbeid'
    | '/sitemap.xml'
    | '/what-is-arancini'
    | '/admin/$slug'
    | '/admin/accounting'
    | '/admin/inquiries'
    | '/admin/newsletter'
    | '/admin/popup'
    | '/en/about'
    | '/en/collaborate'
    | '/en/find-us'
    | '/en/for-bars'
    | '/en/next-popup'
    | '/en/what-is-arancini'
    | '/pilot/leverandor'
    | '/steder/$slug'
    | '/admin'
    | '/en'
    | '/pilot'
    | '/api/seo/notify'
    | '/en/venues/$slug'
    | '/api/public/v1/module/health'
    | '/api/public/v1/module/info'
    | '/api/public/v1/module/organization'
    | '/api/public/v1/module/widgets'
    | '/api/public/v1/module/organization/$orgId'
  id:
    | '__root__'
    | '/'
    | '/a3f8c91e7b4d2f60goldofsicily.txt'
    | '/about'
    | '/admin'
    | '/en'
    | '/finn-oss'
    | '/for-barer'
    | '/next-popup'
    | '/pilot'
    | '/samarbeid'
    | '/sitemap.xml'
    | '/what-is-arancini'
    | '/admin/$slug'
    | '/admin/accounting'
    | '/admin/inquiries'
    | '/admin/newsletter'
    | '/admin/popup'
    | '/en/about'
    | '/en/collaborate'
    | '/en/find-us'
    | '/en/for-bars'
    | '/en/next-popup'
    | '/en/what-is-arancini'
    | '/pilot/leverandor'
    | '/steder/$slug'
    | '/admin/'
    | '/en/'
    | '/pilot/'
    | '/api/seo/notify'
    | '/en/venues/$slug'
    | '/api/public/v1/module/health'
    | '/api/public/v1/module/info'
    | '/api/public/v1/module/organization'
    | '/api/public/v1/module/widgets'
    | '/api/public/v1/module/organization/$orgId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  A3f8c91e7b4d2f60goldofsicilyDottxtRoute: typeof A3f8c91e7b4d2f60goldofsicilyDottxtRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  EnRoute: typeof EnRouteWithChildren
  FinnOssRoute: typeof FinnOssRoute
  ForBarerRoute: typeof ForBarerRoute
  NextPopupRoute: typeof NextPopupRoute
  PilotRoute: typeof PilotRouteWithChildren
  SamarbeidRoute: typeof SamarbeidRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  WhatIsAranciniRoute: typeof WhatIsAranciniRoute
  StederSlugRoute: typeof StederSlugRoute
  ApiSeoNotifyRoute: typeof ApiSeoNotifyRoute
  ApiPublicV1ModuleHealthRoute: typeof ApiPublicV1ModuleHealthRoute
  ApiPublicV1ModuleInfoRoute: typeof ApiPublicV1ModuleInfoRoute
  ApiPublicV1ModuleOrganizationRoute: typeof ApiPublicV1ModuleOrganizationRouteWithChildren
  ApiPublicV1ModuleWidgetsRoute: typeof ApiPublicV1ModuleWidgetsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/what-is-arancini': {
      id: '/what-is-arancini'
      path: '/what-is-arancini'
      fullPath: '/what-is-arancini'
      preLoaderRoute: typeof WhatIsAranciniRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/samarbeid': {
      id: '/samarbeid'
      path: '/samarbeid'
      fullPath: '/samarbeid'
      preLoaderRoute: typeof SamarbeidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pilot': {
      id: '/pilot'
      path: '/pilot'
      fullPath: '/pilot'
      preLoaderRoute: typeof PilotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/next-popup': {
      id: '/next-popup'
      path: '/next-popup'
      fullPath: '/next-popup'
      preLoaderRoute: typeof NextPopupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-barer': {
      id: '/for-barer'
      path: '/for-barer'
      fullPath: '/for-barer'
      preLoaderRoute: typeof ForBarerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finn-oss': {
      id: '/finn-oss'
      path: '/finn-oss'
      fullPath: '/finn-oss'
      preLoaderRoute: typeof FinnOssRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en': {
      id: '/en'
      path: '/en'
      fullPath: '/en'
      preLoaderRoute: typeof EnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a3f8c91e7b4d2f60goldofsicily.txt': {
      id: '/a3f8c91e7b4d2f60goldofsicily.txt'
      path: '/a3f8c91e7b4d2f60goldofsicily.txt'
      fullPath: '/a3f8c91e7b4d2f60goldofsicily.txt'
      preLoaderRoute: typeof A3f8c91e7b4d2f60goldofsicilyDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pilot/': {
      id: '/pilot/'
      path: '/'
      fullPath: '/pilot/'
      preLoaderRoute: typeof PilotIndexRouteImport
      parentRoute: typeof PilotRoute
    }
    '/en/': {
      id: '/en/'
      path: '/'
      fullPath: '/en/'
      preLoaderRoute: typeof EnIndexRouteImport
      parentRoute: typeof EnRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/steder/$slug': {
      id: '/steder/$slug'
      path: '/steder/$slug'
      fullPath: '/steder/$slug'
      preLoaderRoute: typeof StederSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pilot/leverandor': {
      id: '/pilot/leverandor'
      path: '/leverandor'
      fullPath: '/pilot/leverandor'
      preLoaderRoute: typeof PilotLeverandorRouteImport
      parentRoute: typeof PilotRoute
    }
    '/en/what-is-arancini': {
      id: '/en/what-is-arancini'
      path: '/what-is-arancini'
      fullPath: '/en/what-is-arancini'
      preLoaderRoute: typeof EnWhatIsAranciniRouteImport
      parentRoute: typeof EnRoute
    }
    '/en/next-popup': {
      id: '/en/next-popup'
      path: '/next-popup'
      fullPath: '/en/next-popup'
      preLoaderRoute: typeof EnNextPopupRouteImport
      parentRoute: typeof EnRoute
    }
    '/en/for-bars': {
      id: '/en/for-bars'
      path: '/for-bars'
      fullPath: '/en/for-bars'
      preLoaderRoute: typeof EnForBarsRouteImport
      parentRoute: typeof EnRoute
    }
    '/en/find-us': {
      id: '/en/find-us'
      path: '/find-us'
      fullPath: '/en/find-us'
      preLoaderRoute: typeof EnFindUsRouteImport
      parentRoute: typeof EnRoute
    }
    '/en/collaborate': {
      id: '/en/collaborate'
      path: '/collaborate'
      fullPath: '/en/collaborate'
      preLoaderRoute: typeof EnCollaborateRouteImport
      parentRoute: typeof EnRoute
    }
    '/en/about': {
      id: '/en/about'
      path: '/about'
      fullPath: '/en/about'
      preLoaderRoute: typeof EnAboutRouteImport
      parentRoute: typeof EnRoute
    }
    '/admin/popup': {
      id: '/admin/popup'
      path: '/popup'
      fullPath: '/admin/popup'
      preLoaderRoute: typeof AdminPopupRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/newsletter': {
      id: '/admin/newsletter'
      path: '/newsletter'
      fullPath: '/admin/newsletter'
      preLoaderRoute: typeof AdminNewsletterRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/inquiries': {
      id: '/admin/inquiries'
      path: '/inquiries'
      fullPath: '/admin/inquiries'
      preLoaderRoute: typeof AdminInquiriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/accounting': {
      id: '/admin/accounting'
      path: '/accounting'
      fullPath: '/admin/accounting'
      preLoaderRoute: typeof AdminAccountingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/$slug': {
      id: '/admin/$slug'
      path: '/$slug'
      fullPath: '/admin/$slug'
      preLoaderRoute: typeof AdminSlugRouteImport
      parentRoute: typeof AdminRoute
    }
    '/en/venues/$slug': {
      id: '/en/venues/$slug'
      path: '/venues/$slug'
      fullPath: '/en/venues/$slug'
      preLoaderRoute: typeof EnVenuesSlugRouteImport
      parentRoute: typeof EnRoute
    }
    '/api/seo/notify': {
      id: '/api/seo/notify'
      path: '/api/seo/notify'
      fullPath: '/api/seo/notify'
      preLoaderRoute: typeof ApiSeoNotifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/module/widgets': {
      id: '/api/public/v1/module/widgets'
      path: '/api/public/v1/module/widgets'
      fullPath: '/api/public/v1/module/widgets'
      preLoaderRoute: typeof ApiPublicV1ModuleWidgetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/module/organization': {
      id: '/api/public/v1/module/organization'
      path: '/api/public/v1/module/organization'
      fullPath: '/api/public/v1/module/organization'
      preLoaderRoute: typeof ApiPublicV1ModuleOrganizationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/module/info': {
      id: '/api/public/v1/module/info'
      path: '/api/public/v1/module/info'
      fullPath: '/api/public/v1/module/info'
      preLoaderRoute: typeof ApiPublicV1ModuleInfoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/module/health': {
      id: '/api/public/v1/module/health'
      path: '/api/public/v1/module/health'
      fullPath: '/api/public/v1/module/health'
      preLoaderRoute: typeof ApiPublicV1ModuleHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/module/organization/$orgId': {
      id: '/api/public/v1/module/organization/$orgId'
      path: '/$orgId'
      fullPath: '/api/public/v1/module/organization/$orgId'
      preLoaderRoute: typeof ApiPublicV1ModuleOrganizationOrgIdRouteImport
      parentRoute: typeof ApiPublicV1ModuleOrganizationRoute
    }
  }
}

interface AdminRouteChildren {
  AdminSlugRoute: typeof AdminSlugRoute
  AdminAccountingRoute: typeof AdminAccountingRoute
  AdminInquiriesRoute: typeof AdminInquiriesRoute
  AdminNewsletterRoute: typeof AdminNewsletterRoute
  AdminPopupRoute: typeof AdminPopupRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminSlugRoute: AdminSlugRoute,
  AdminAccountingRoute: AdminAccountingRoute,
  AdminInquiriesRoute: AdminInquiriesRoute,
  AdminNewsletterRoute: AdminNewsletterRoute,
  AdminPopupRoute: AdminPopupRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface EnRouteChildren {
  EnAboutRoute: typeof EnAboutRoute
  EnCollaborateRoute: typeof EnCollaborateRoute
  EnFindUsRoute: typeof EnFindUsRoute
  EnForBarsRoute: typeof EnForBarsRoute
  EnNextPopupRoute: typeof EnNextPopupRoute
  EnWhatIsAranciniRoute: typeof EnWhatIsAranciniRoute
  EnIndexRoute: typeof EnIndexRoute
  EnVenuesSlugRoute: typeof EnVenuesSlugRoute
}

const EnRouteChildren: EnRouteChildren = {
  EnAboutRoute: EnAboutRoute,
  EnCollaborateRoute: EnCollaborateRoute,
  EnFindUsRoute: EnFindUsRoute,
  EnForBarsRoute: EnForBarsRoute,
  EnNextPopupRoute: EnNextPopupRoute,
  EnWhatIsAranciniRoute: EnWhatIsAranciniRoute,
  EnIndexRoute: EnIndexRoute,
  EnVenuesSlugRoute: EnVenuesSlugRoute,
}

const EnRouteWithChildren = EnRoute._addFileChildren(EnRouteChildren)

interface PilotRouteChildren {
  PilotLeverandorRoute: typeof PilotLeverandorRoute
  PilotIndexRoute: typeof PilotIndexRoute
}

const PilotRouteChildren: PilotRouteChildren = {
  PilotLeverandorRoute: PilotLeverandorRoute,
  PilotIndexRoute: PilotIndexRoute,
}

const PilotRouteWithChildren = PilotRoute._addFileChildren(PilotRouteChildren)

interface ApiPublicV1ModuleOrganizationRouteChildren {
  ApiPublicV1ModuleOrganizationOrgIdRoute: typeof ApiPublicV1ModuleOrganizationOrgIdRoute
}

const ApiPublicV1ModuleOrganizationRouteChildren: ApiPublicV1ModuleOrganizationRouteChildren =
  {
    ApiPublicV1ModuleOrganizationOrgIdRoute:
      ApiPublicV1ModuleOrganizationOrgIdRoute,
  }

const ApiPublicV1ModuleOrganizationRouteWithChildren =
  ApiPublicV1ModuleOrganizationRoute._addFileChildren(
    ApiPublicV1ModuleOrganizationRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  A3f8c91e7b4d2f60goldofsicilyDottxtRoute:
    A3f8c91e7b4d2f60goldofsicilyDottxtRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  EnRoute: EnRouteWithChildren,
  FinnOssRoute: FinnOssRoute,
  ForBarerRoute: ForBarerRoute,
  NextPopupRoute: NextPopupRoute,
  PilotRoute: PilotRouteWithChildren,
  SamarbeidRoute: SamarbeidRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  WhatIsAranciniRoute: WhatIsAranciniRoute,
  StederSlugRoute: StederSlugRoute,
  ApiSeoNotifyRoute: ApiSeoNotifyRoute,
  ApiPublicV1ModuleHealthRoute: ApiPublicV1ModuleHealthRoute,
  ApiPublicV1ModuleInfoRoute: ApiPublicV1ModuleInfoRoute,
  ApiPublicV1ModuleOrganizationRoute:
    ApiPublicV1ModuleOrganizationRouteWithChildren,
  ApiPublicV1ModuleWidgetsRoute: ApiPublicV1ModuleWidgetsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
